name: Build and Push Docker Image

on:
    push:
      branches:
        - master
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx for building images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to DockerHub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dashboard:${{ github.sha }} .
    
    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dashboard:${{ github.sha }}

    # (Optional) Add the 'latest' tag to the image
    - name: Tag Docker image with 'latest'
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/dashboard:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/dashboard:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/dashboard:latest